- input:
    project: "juneboku"
    inclusion_page_title_patterns:
      - "^\\d{4}-\\d{2}-\\d{2} \\w{3} : .+"
    exclusion_page_title_patterns:
      - "\\(書きかけ\\)"
  output:
    feed_title: "純朴日記"
    feed_description: "junebokuが2019年8月23日から書き続けている毎日更新の日記です"
    feed_author: "juneboku"
    file_name: "nikki"
- input:
    project: "juneboku"
    inclusion_page_title_patterns:
      - ".+"
    exclusion_page_title_patterns:
      - "^\\d{4}-\\d{2}-\\d{2} \\w{3} : .+"
      - "\\(書きかけ\\)"
  output:
    feed_title: "純朴雑記"
    feed_description: "junebokuが雑に書いたものたち"
    feed_author: "juneboku"
    file_name: "zakki"
- input:
    project: "june29"
    inclusion_page_title_patterns:
      - "^\\d{4}-\\d{2}-\\d{2} \\w{3} : .+"
    exclusion_page_title_patterns:
      - "\\(書きかけ\\)"
  output:
    feed_title: "旧・純朴日記(更新停止)"
    feed_description: "junebokuが2019年8月23日から書き続けている毎日更新の日記です"
    feed_author: "juneboku"
    file_name: "nikki"
- input:
    project: "june29"
    inclusion_page_title_patterns:
      - ".+"
    exclusion_page_title_patterns:
      - "^\\d{4}-\\d{2}-\\d{2} \\w{3} : .+"
      - "\\(書きかけ\\)"
  output:
    feed_title: "旧・純朴雑記(更新停止)"
    feed_description: "junebokuが雑に書いたものたち"
    feed_author: "juneboku"
    file_name: "zakki"
- input:
    project: "sugie"
    inclusion_page_title_patterns:
      - "\\d{8} .+"
    exclusion_page_title_patterns:
      - "書きかけ$"
  output:
    feed_title: "すぎえ日記"
    feed_description: "すぎえの日記です"
    feed_author: "sugiwe"
    file_name: "diary"
- input:
    project: "tanaken0515"
    inclusion_page_title_patterns:
      - "^\\d{4}-\\d{2}-\\d{2}: .+"
    exclusion_page_title_patterns:
      - "タイトル$"
  output:
    feed_title: "たなけん日記"
    feed_description: "たなけんの日記です"
    feed_author: "tanaken0515"
    file_name: "nikki"
- input:
    project: "tanaken0515"
    inclusion_page_title_patterns:
      - ".+"
    exclusion_page_title_patterns:
      - "^\\d{4}-\\d{2}-\\d{2}: .+"
  output:
    feed_title: "たなけん雑記"
    feed_description: "たなけんの雑記です"
    feed_author: "tanaken0515"
    file_name: "zakki"
