name: Preview on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  run-script-and-comment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3

    - name: Preview result
      run: |
        echo "```" > preview.txt
        ruby generate.rb >> preview.txt
        echo "```" >> preview.txt

    - name: Post comment on Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr comment ${{ github.event.pull_request.html_url }} -F preview.txt
