name: Preview on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-script-and-comment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3

    - name: Run script
      id: run-script
      run: |
        output=$(ruby generate.rb)
        echo "result=$output" >> $GITHUB_ENV

    - name: Comment PR
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const output = process.env.result
          const issue_number = context.issue.number
          github.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "```" + output + "```",
          })
