name: Preview on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-script-and-comment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3

    - name: Run script
      id: run-script
      run: |
        echo "preview<<-EOF" >> "$GITHUB_OUTPUT"
        echo "```"           >> "$GITHUB_OUTPUT"
        ruby generate.rb     >> "$GITHUB_OUTPUT"
        echo "```"           >> "$GITHUB_OUTPUT"
        echo "-EOF"          >> "$GITHUB_OUTPUT"
        cat "$GITHUB_OUTPUT"

    - name: Comment PR
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = process.env.result
          const issue_number = context.issue.number
          github.rest.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "GitHub Actions!"
          })
